---
name: Test action
on: workflow_call
jobs:
  test-action:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    permissions: {}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - run: npm ci
      - run: npm run build
      - uses: ./
        with:
          github_token: ${{github.token}}
          files: README.md
