---
name: test (workflow_call)
on:
  workflow_call:
    secrets:
      gh_app_id:
        required: true
      gh_app_private_key:
        required: true
permissions: {}
jobs:
  path-filter:
    # Get changed files to filter jobs
    timeout-minutes: 10
    outputs:
      renovate-config-validator: ${{steps.changes.outputs.renovate-config-validator}}
      changed_files: ${{steps.changes.outputs.all_files}}
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: changes
        with:
          list-files: shell
          filters: |
            renovate-config-validator:
              - renovate.json5
              - .github/workflows/test.yaml
              - .github/workflows/wc-renovate-config-validator.yaml
            all:
              - "**"

  renovate-config-validator:
    uses: ./.github/workflows/wc-renovate-config-validator.yaml
    needs: path-filter
    if: needs.path-filter.outputs.renovate-config-validator == 'true'
    permissions:
      contents: read

  test:
    uses: ./.github/workflows/wc-test.yaml
    needs: path-filter
    permissions: {}
    with:
      files: ${{needs.path-filter.outputs.changed_files}}
    secrets:
      gh_app_id: ${{secrets.gh_app_id}}
      gh_app_private_key: ${{secrets.gh_app_private_key}}

